import BarcodeScanner from '@/components/BarcodeScanner'
import { TextResult } from 'dynamsoft-javascript-barcode/dist/types/interface/textresult';
import Head from 'next/head'
import React from 'react';
import homeStyles from '../styles/Home.module.css';

export default function Home() {
  const [isActive,setIsActive] = React.useState(true);
  const toggleScanning = () => {
    setIsActive(!isActive);
  }

  const onScanned = (results:TextResult[]) => {
    console.log(results);
  }

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <div>
          <div className={homeStyles.barcodeScanner}>
            <BarcodeScanner
              isActive={isActive}
              onScanned={(results) => onScanned(results)}
            ></BarcodeScanner>
          </div>
          <button onClick={toggleScanning}>{isActive ? "Stop Scanning" : "Start Scanning"}</button>
        </div>
      </main>
    </>
  )
}
