import BarcodeScanner from '@/components/BarcodeScanner'
import { TextResult } from 'dynamsoft-javascript-barcode/dist/types/interface/textresult';
import Head from 'next/head'
import React from 'react';
import homeStyles from '../styles/Home.module.css';
import fs from 'fs';

export async function getServerSideProps() {
  let license:string = "";
  license = fs.readFileSync('src/license.txt').toString();
  return { props: { license:license } };
}

export default function Home(props:any) {
  const [isActive,setIsActive] = React.useState(false);
  const toggleScanning = () => {
    setIsActive(!isActive);
  }

  React.useEffect(()=>{
    console.log(props);
  },[]);

  const onScanned = (results:TextResult[]) => {
    if (results.length>0) {
      let text = "";
      for (let index = 0; index < results.length; index++) {
        const result = results[index];
        text = text + result.barcodeFormatString + ": " + result.barcodeText + "\n";
      }
      alert(text);
      setIsActive(false);
    }
  }

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <div className={homeStyles.app}>
          <h2>Next.js Barcode Scanner</h2>
          <button onClick={toggleScanning}>{isActive ? "Stop Scanning" : "Start Scanning"}</button>
          <div className={homeStyles.barcodeScanner}>
            <BarcodeScanner
              license={props.license}
              isActive={isActive}
              onScanned={(results) => onScanned(results)}
            ></BarcodeScanner>
          </div>
        </div>
      </main>
    </>
  )
}
